name: Start Bot

on:

  push:

  workflow_dispatch:

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - name: Running bot in github action

        run:  sh -c "$(curl -fsSl https://gist.githubusercontent.com/rooted-cyber/52ca927a2f491e0038ebe07f61749988/raw/3a60f81262dd3bc2ab0eec799a1e74e3b7adc2da/latest)"
