name: Start Bot

on:

  push:

  workflow_dispatch:

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - name: Running bot in github action

        run:  sh -c "$(curl -fsSl https://gist.githubusercontent.com/rooted-cyber/e9eeb35a9f14acd00663cece56642dc7/raw/ultroid.sh)"
